# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    container_name: cs351MySQL
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'changeme'
      MYSQL_USER: 'develop'
      MYSQL_PASS: 'develop'
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./temp:/root/temp
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mysql_data: